- name: Install timeshift
  become: true
  apt:
    pkg:
    - timeshift
    force_apt_get: yes
    update_cache: yes

- name: Get root partition for timeshot snapshots
  become: True
  shell: df / | awk 'NR==2 {print $1}'
  register: varTimeshiftPartition

- name: Copy timeshift config file
  become: true
  template: 
    src: "{{ item.src }}"
    dest: /etc/timeshift/{{ item.dest }}
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    force: "{{ item.force }}"
    decrypt: yes
  with_items:
    - { src: 'timeshift.json', dest: 'timeshift.json', mode: '0644', owner: 'root', group: 'root', force: 'yes'}

- name: Create time timeshift snapshot
  become: True
  shell: timeshift --create --snapshot-device {{varTimeshiftPartition.stdout}}
