- name: Delay up to an hour to confirm unattended or apt not being 
  become: true
  shell: lsof /var/lib/dpkg/lock-frontend
  register: aptBusyResult
  retries: 60
  delay: 60
  until: aptBusyResult.rc == 1
  failed_when: aptBusyResult.rc >= 2
  changed_when: false

- name: Download xm
  become: true
  ansible.builtin.get_url:
    url: http://intranet.cymcore.com/files/software/ubuntu/xm.deb
    dest: /tmp/
    mode: '0770'

- name: Copy xm vars
  become: true
  copy:
    src: 80-xm.conf
    dest: /etc/environment.d/
    owner: root
    group: root
    mode: '0755'
    decrypt: true

- name: Install xm
  become: True
  shell: apt install /tmp/xm.deb

- name: Install flatpak apps
  become: True
  vars:
    flatpakAppsToInstall:
      - com.github.micahflee.torbrowser-launcher
      - com.microsoft.Edge
      - org.chromium.Chromium
      - org.videolan.VLC
      - org.gimp.GIMP
      - org.inkscape.Inkscape
      - org.flameshot.Flameshot
      - org.kde.kdenlive
  shell: flatpak install flathub {{item}} -y
  with_items: "{{flatpakAppsToInstall}}"