- name: New user message
  debug:
    msg: User ptimme01 being created

- name: Prompt for user password
  pause:
    prompt: Enter user password
    echo: false
  register: userOsPassword
  no_log: true
 
- name: Add user primary groups
  become: true
  ansible.builtin.group:
    name: ptimme01
    state: present
    gid: 2001

- name: Add user
  become: true
  ansible.builtin.user:
    name: ptimme01
    comment: Paul Timmerman
    state: present
    uid: 2001
    group: ptimme01
    groups: sudo
    shell: /bin/bash
    password: "{{ userOsPassword.user_input | password_hash('sha512') }}"
  no_log: true

- name: Creates directories in home
  tags: run
  become: true
  file:
    path: /home/ptimme01/{{item.dest}}
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { dest: 'appimage', mode: '0770', owner: 'ptimme01', group: 'ptimme01'}
    - { dest: 'scm', mode: '0770', owner: 'ptimme01', group: 'ptimme01'}
    

